require 'rubygems'
require 'bundler'
require 'nokogiri'
require 'socket'
require 'open-uri'
require 'active_record'
require 'active_support'
require 'active_support/core_ext'
require 'pp'
require 'csv'
require 'yaml'
require 'date'
require 'json'
require 'open_uri_redirections'
require 'mechanize'
require 'aws-sdk'
require 'numerals_jp'

